Change Composer Worker Memory Size to the maximum allowed 13 GB.
Updating to 16 GB returned an error when Terraform tried to apply: 

Error: googleapi: Error 400: Found 1 problem:
	1) Worker memory must be between 2.00GB and 13.00GB for given vCpu., badRequest

[#4198]